server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
      resource-server:
        jwt:
          jws-algorithm: RS256
          public-key-location: file:./jwt_key.pub
  datasource:
    url: jdbc:postgresql://localhost:5432/iqueue
    username: ${DB_USER:user1}
    password: ${DB_PASS:pass1}
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

jwt:
  publicKey: ${JWT_PUBLIC_KEY:jwt_key.pub}
  privateKey: ${JWT_PRIVATE_KEY:jwt_key}
  secret: ${JWT_SECRET:iqueue_secret}
  iss: ums
  sub: iqueue
  # JWT valid time, the unit is minute.
  duration: ${JWT_VALID_TIME:90}
